account/urls.py
from django.urls import path
from django.urls import include, re_path
from . import views

app_name = 'account'
urlpatterns = [
    
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("activate/<uidb64>/<token>/", views.activate, name='activate'),
    path("setting",views.account,name="account"),
    path("discussion", views.discussion, name="discussion"),
    path("notification",views.notification, name="notification"),
    path("job-response/<int:jobrequestid>",views.job_response,name="job_response"),
    path("updateprofile/<str:section>/<str:newvalue>", views.update_account, name="update_account"),
    path("updateprofile/<str:section>", views.update_account, name="update_account"),
    path("profile/<str:username>-<int:id>",views.user_profile,name="user_profile"),

]

advertisement/urls.py
  
from django.urls import path
from . import views

app_name = 'advertisement'
urlpatterns = [
    
    path("", views.index, name="index"),
    path("jobsearch/<str:type>", views.jobsearch, name="jobsearch"),

    path("job-profile/<slug:type>-<int:id>", views.job_profile, name="job_profile"),
    path("job-application/<int:id>", views.job_application, name="job_application"),   

    path("schedule-appointment/<int:id>",views.fix_appointment,name="fix_appointment"),
    path("appointment",views.appointment,name="appointment"),
    path("appointment/<int:id>",views.appointment,name="appointment"),
    path("review/appointment-<int:id>",views.review,name="review"),

    path("<str:username>/", views.user_account, name="user_account"),
    path("<str:username>/<slug:section>", views.user_account, name="user_account"),
    path("<str:username>/section/<slug:section>",views.section, name="section"),
    path("<str:username>/section/<slug:section>/address/", views.current_address, name="current_address"),
    path("<str:username>/section/<slug:section>/savedaddress/", views.saved_address, name="saved_address"),
    path("<str:username>/section/<slug:section>/add-address/", views.add_new_address, name="add_new_address"),
    

]

project5/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('advertisement/', include("advertisement.urls")),
]

advertisement/forms.py
from django.forms import ModelForm
from advertisement.models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms
from datetime import date

class SavedAddressForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super(SavedAddressForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'new_job_form_components'

    class Meta:
        model = SavedAddress
        exclude = ['User']
        widgets = {
            
        'Line1': forms.TextInput(attrs={'name':'ADDRESS_LINE1','id':'autocomplete','placeholder':'Line 1','class':'profile_form_components','autocomplete':'street-address','aria-autocomplete':'list'}),
        'Line2': forms.TextInput(attrs={'name':'sublocality_level_2','id':'sublocality_level_2','placeholder':'Line 2','class':'profile_form_components','autocomplete':'address-level1'}),
        'City': forms.TextInput(attrs={'name':'locality','id':'locality','placeholder':'City','class':'profile_form_components','autocomplete':'address-level2'}),
        'State': forms.TextInput(attrs={'name':'administrative_area_level_1','id':'administrative_area_level_1','placeholder':'State','class':'profile_form_components','autocomplete':'address-level1'}),
        'Country': forms.TextInput(attrs={'name':'country','id':'country','placeholder':'Country','class':'profile_form_components','autocomplete':'address-level2'}),
        'Zipcode': forms.TextInput(attrs={'name':'postal_code','id':'postal_code','placeholder':'Postal Code','class':'profile_form_components'}),
       
        }


def start_date():
    date_today = date.today().strftime('%Y-%m-%d')
    return date_today


class JobForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = ' new_job_form_components'
            
        self.fields['Date'] = forms.DateField()
   
    class Meta:
        model = Job
        exclude = ['Customer','Status']
   
        widgets = {
        
        'Description': forms.Textarea(attrs={'placeholder':'Enter Description','class':'col-sm-11','style':'top:2rem'}),
        'Date': forms.DateInput(format=('%m:%d:%Y'), attrs={ 'placeholder':'Select a date', 'type':'date', 'value':start_date, 'min':start_date}),
        'Time': forms.TimeInput(format=('%H:%M'), attrs={ 'placeholder':'Select a time', 'type':'time'}),
        'Location' : forms.HiddenInput(attrs={'name':'Location','class':'col-sm-11','placeholder': 'Enter location','disabled':'true'}),
  
        }

  


class JobapplicationForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super(JobapplicationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():

            visible.field.widget.attrs['class'] = 'form-control  new_job_form_components'

    class Meta:
        model = JobRequest
        exclude = ['Technician','Job']

        widgets = {
            'Quote': forms.Textarea(attrs={'cols':'100','placeholder':'Enter your quote ','class':'col-lg-12','style':'top:2rem'}),
            'Date': forms.DateInput(format='%m:%d:%Y',attrs={'placeholder':'Select a date', 'type':'date', 'style':'margin-top:2rem' ,'id':'datepicker','min':start_date,'value':start_date }),
            'Time': forms.TimeInput(format='%H:%M',attrs={'placeholder':'Select a time', 'type':'time','style':'top:2rem'}),
        }

    
class JobresponseForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super(JobresponseForm, self).__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control  new_job_form_components'
        
    class Meta:
        model = JobResponse
        exclude = ['Customer','Jobrequest','Response']
    
        widgets = {
            
            'Message': forms.Textarea(attrs={'cols':'100','placeholder':'Enter your Message with date and time','class':'col-lg-12','style':'top:2rem'}) , 
            'Date': forms.DateInput(format='%m:%d:%Y',attrs={'placeholder':'Select a date', 'type':'date', 'style':'margin-top:2rem' ,'id':'datepicker','min':start_date,'value':start_date }),
            'Time': forms.TimeInput(format='%H:%M',attrs={'placeholder':'Select a time', 'type':'time','style':'top:2rem'}),

            }

class ReviewForm(forms.ModelForm):
    
    def __init__(self,*args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)


        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control  new_job_form_components'

    class Meta:
        model = Review
        exclude = ['Reviewer','Reviewee',"Appointment",'Rating']
   
        widgets = {
        
        'Comment': forms.Textarea(attrs={'placeholder':'Enter your comments','class':'col-sm-11','style':'top:2rem'}),
        
        }

advertisement/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseRedirect,Http404,HttpRequest
from django.contrib.auth.decorators import login_required
from django.db import models
from django.urls import reverse
from . import forms
import account.models
import account.util
from collections import deque
from .models import *
from django.db.models import Q
import json
from json import dumps 
from django.template import loader
from functools import reduce
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
from datetime import date
# Create your views here.
jobsearch_stack=deque()
request_method_get =(
    ('GET','get'),
   
)
request_method_post =(
    ('POST','post'),
   
)
def paginate(request,argument):

    """
    1. Function to paginate - maximum 5 count on a page
    """
    page_number = request.GET.get('page',1)
    paginator = Paginator(argument, 5) 

    try:
        paginated_argument = paginator.page(page_number)
    except PageNotAnInteger:
        paginated_argument = paginator.page(1)
    except EmptyPage:
        paginated_argument = paginator.page(paginator.num_pages)
    
    return paginated_argument

def index(request):

    """
    index -show all jobs 
    """
 
    if request.user.is_authenticated:
        #clear search stack
        jobsearch_stack.clear()
        
        jobs = paginate(request,Job.objects.all().order_by('Date'))
        return render(request,"advertisement/index.html",{
            "jobs":jobs,
 
            "job_requests_ids":list(JobRequest.objects.filter(Technician=request.user).values_list("Job",flat=True)),
            })
        
    else:
        return HttpResponseRedirect(reverse("account:login"))

def job_profile(request,**args):
    """
    show job profile
    """
    if request.user.is_authenticated:
        #get job id from url
        job_id = args["id"]
    
        #check if request already sent 
        request_sent = check_job_request_sent(request,job_id)
 


        # get job location
        inst = Job.objects.get(id=job_id)
        loc = inst.Location
        
        #render to webpage
        return render(request,"advertisement/job-profile.html",{
            "job":inst,
            "location":loc,
            'request_sent':request_sent,
            
            })
        
    else:
        return HttpResponseRedirect(reverse("account:login"))
status = ["OPEN","PENDING"]
job_type = ['ELECTRICAL', 'PLUMBING','HANDYMAN']

@login_required
def jobsearch(request,**args):
    """  
    Job search via filter
    Filter options: Job type and Job status
    jobsearch_stack is Doubly Ended Queue

    """
    
    if request.user.is_authenticated:
        searchby = args["type"]
        if searchby not in jobsearch_stack:
            jobsearch_stack.append(searchby)

        else:
            jobsearch_stack.remove(searchby)
        result = ""
        status_list = []
        job_list = []
        for i in jobsearch_stack:
            if i in status:
                status_list.append(i)
            if i in job_type:
                job_list.append(i)

        if len(status_list) == 0:
            status_list = status
        if len(job_list) == 0:
            job_list = job_type
        
        #ignore case of status/job type for lookup
        j_list = map(lambda jname: Q(Job_type__iexact=jname), job_list)
        j_list = reduce(lambda a, b: a | b, j_list)
        
        s_list = map(lambda sname: Q(Status__iexact=sname), status_list)
        s_list = reduce(lambda a, b: a | b, s_list)
   
        result = {"result":list(Job.objects.filter(j_list,s_list).order_by('Date').values()),
                  "job_requested_ids": list(JobRequest.objects.filter(Technician=request.user).values_list("Job",flat=True))}
        

        
        response = json.dumps(result,default=str)
        return HttpResponse(response,content_type = "application/json")
        

    else:
        return HttpResponseRedirect(reverse("account:login"))

def check_job_request_sent(request,job_id):
    """
    checks if job request had already been sent by user
    """
    # job instance
    job_instance = Job.objects.get(id=job_id)     
                   
    # check if user had already sent request 
    if JobRequest.objects.filter(Technician = request.user, Job=job_instance).exists():
        return True
    return False

@login_required
def job_application(request,**args):

    """
    1. Quote -charfield
    2. Available dates and time (date and time range)
    
    """

    
    job_id = args["id"] 
    if (any(request.method in i for i in request_method_get)):

        form= forms.JobapplicationForm()
        return render(request, "advertisement/job-application.html",{
            "applicationForm":form,
            "id":job_id,

        })
        
    if (any(request.method in i for i in request_method_post)):

        error =""
        message=""
        form= forms.JobapplicationForm(request.POST)
        if form.is_valid():
            Quote = form.cleaned_data["Quote"]
            Date = form.cleaned_data["Date"]
            Time = form.cleaned_data["Time"]
            Amount = form.cleaned_data["Amount"]
            Currency = form.cleaned_data["Currency"]


        try:
            #get job instance
            job_instance = Job.objects.get(id=job_id)     

            #user must be technician 
            if account.util.get_user_role(request) == "Technician":
                if check_job_request_sent(request,job_id): 
                    #previous job request exist so 
                    error = "Request already sent!"
                else:

                    #create job request
                    jobrequest = JobRequest.objects.create(Technician = request.user,Job=job_instance,Quote=Quote,Date=Date,Time=Time,Amount=Amount,Currency=Currency)
                    jobrequest.save()

                    #create discussion for job owner (customer)

                    #get customer instance
                    customer_instance = account.models.User.objects.get(id=job_instance.Customer.id)

                    #create discussion for customer
                    discussion = account.models.Discussion.objects.create(User=customer_instance,Jobrequest=jobrequest,Jobresponse=None,Checked=False)
                    discussion.save()

                    request.session['has_checked'] = False
           

                    message="Message sent!"
            else:
                # Customers not authorised to sent job request
                raise Http404("Not authorised")
        except:
            error = "Unable to process"

        
        return render(request, "advertisement/job-application.html",{
            "message":message,
            "error" :error,
            "id":job_id,

        })
    raise Http404("Not Found")

@login_required
def user_account(request,**args):

    if request.user.is_authenticated:
        
        initialcategory = ""
        if "section" in args.keys():
            initialcategory=args["section"]
        if (any(request.method in i for i in request_method_get)):
            # new-job form
            form = forms.JobForm()
            return render(request, "advertisement/ad.html",{
                "initialcategory":initialcategory,
                "Jobform":form,
            })
                
        if (any(request.method in i for i in request_method_post)):
            # new-job form
            form = forms.JobForm(request.POST)
            if form.is_valid():
                job = form.save(commit=False)
                job.Customer = request.user
                job.Status = 'OPEN'
                job.save()
                
                return HttpResponseRedirect(reverse("advertisement:index"))
            else:
                return render(request, "advertisement/ad.html",{
                "initialcategory":initialcategory,
                "Jobform":form,
            })

       

def section(request,**args):
    #navigate to sections in user_account

    result =""
    if request.user.is_customer:
        #get job profile
        job = Job.objects.filter(Customer=request.user)
    if args["section"] == "ads":
        if request.user.is_customer:
            result = {"result":list(job.order_by('Date').values())}
        else:
            raise Http404("Un authorised to perform this action")
    if args["section"] == "appointments":
      
        result = {"result": list(retrieve_appointments(request).values())}

    if args["section"] == "reviews":
        review =Review.objects.filter(Reviewee = request.user)
        result = {
            "result": list(review.values("Comment","Rating"))

            }
    if args["section"] == "given_reviews":
        givenreview =Review.objects.filter(Reviewer = request.user)
        result = {
            "result": list(givenreview.values("Comment","Rating"))

            }

    response = json.dumps(result,default=str)
    return HttpResponse(response,content_type = "application/json")


@login_required
def current_address(request,**args):

    try:
        user_address = account.models.Address.objects.get(User = request.user.id)
        #get user's saved current address form Saved address model
        current_address = SavedAddress.objects.filter(id=user_address.Useraddress.id)

    except:
        current_address = None

    #if there is no saved current address, show result as none
    if current_address!=None:
        result = {"result":list(current_address.values())}
    else:
        result ={"result":None}

    response = json.dumps(result,default=str)
    return HttpResponse(response,content_type = "application/json")

@login_required
def saved_address(request,**args):

    try:
        #check if user has set any current address

        if account.models.Address.objects.filter(User = request.user.id):
            user_address = account.models.Address.objects.get(User = request.user.id)
        else:

advertisement/templates/advertisement/ad.html
{% extends "layout.html" %}

{% block title %}
    Posts
{% endblock %}

{% load static %}
{% load crispy_forms_tags %}
{% block head %}


<script>

    var initialcategory = "{{initialcategory}}"

       if (initialcategory == ""){
        initialcategory = localStorage.getItem('previoussection')
        
    }

</script>


{%endblock%}
{% block body %}

<div id="index" class="container-fluid">
    <div class="row">
        <div class="col-md-3 col-xl-2 d-flex left d-md-block    bd-highlight  sidebar"  id = "mini-nav">
        <!-- <nav class = "navbar col-md-3 col-lg-2 navbar-expand-lg navbar-light d-flex bd-highlight d-md-block  sidebar collapse" id = "mini-nav"> -->
            <div class="position-sticky pt-3">
                <div class="col-xs-12 ">
                    {%if request.user.is_customer == True %}
                    <ul class="navbar-nav flex-column">
                    
                        <li class="nav-item">
                        
                            <a class="btn btn-link active" id="button" data-section="new-job">Post a new job</a>
                        </li>
                    </ul>
                    <hr>
                    <ul class="navbar-nav flex-column">
                        <li class="nav-item">
                            <a class="btn btn-link" id="button"  data-section="ads">Ads</a>

                        </li>
                    </ul>
                    <hr>
                    
                    {%endif%}
                    <ul class="navbar-nav flex-column ">
                        <li class="nav-item">
                            <a class="btn btn-link" id="button"  data-section="appointments">Appointments</a>

                        </li>
                    </ul>
                    <hr>
                    
                
                    <ul class="navbar-nav flex-column ">
                        <li class="nav-item">
                    
                            <button class="btn btn-link" id="button" data-section="reviews">Reviews</button>
                        </li>
                    </ul>
                    <hr> 
           

         
                    <ul class="navbar-nav flex-column ">
                        <li class="nav-item">
                            <button class="btn btn-link" id="button"  data-section="given_reviews">Given Reviews</button>

                        </li>
                    </ul> 
                   
                </div>
            </div>
        <!-- </nav> -->
      
        </div>
          
        <div class="col-md-9 col-xl-10 right mx-md-auto">
        <main class=" px-md-4 ">  
           
                
                <div id ="new-job-form" class="d-none">
                   
                
                        {%if Jobform %}
                            <form method="post" action="{% url 'advertisement:user_account' username=user.username|slugify  %}" id="newjob">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-12 mb-0">
                                    {{Jobform.Job_type|as_crispy_field }}
                                    </div>
                                    <div class="form-group col-md-12 mb-0">
                                    {{Jobform.Description|as_crispy_field }}
                                    </div>
                                </div>
            
                                <div class="form-row">
                                
                                    <div class="form-group col-md-6 mb-0">
                                    {{Jobform.Date|as_crispy_field }}
                                    </div>
                                    <div class="form-group col-md-6 mb-0">
                                    {{Jobform.Time|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12 mb-0">
                                        {{Jobform.Priority|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="form-row">
                                <div class="form-group col-md-6 mb-0">
                                    {{Jobform.Amount|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-6 mb-0">
                                    {{Jobform.Currency|as_crispy_field }}
                                </div>    
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                        {{Jobform.Technician_experience_preference|as_crispy_field }}
                                    </div>
                                    <div class="col-md-6 mb-0">
                                        {{Jobform.Licence|as_crispy_field }}
                                        
                                    </div>
                                </div>
                                
                                
                                
                                <div class="form-row">
                                    <div class="form-group col-md-6 mb-0">
                                
                                        <label for="location">Choose a Location</label>
                                        <input type ="text" name ="display_location" id= "display_location" class = "form-control new_job_form_components " placeholder="Select a Location from below" disabled>
                                    </div>
                                    <div class=" form-group col-md-6 mb-0">
                                        {{Jobform.Location}}

                                    </div>
                                </div>
                                
            
            
                                <div class="form-row">
                                <div class="form-group col-md-12" >          
                                    <fieldset class="role" > 
                
                                    <label for="role">Choose a Address</label>
                                        <div class="flex-container">
                                            <input type="radio" name="role" value="current_address" required=True data-toggle="collapse" data-target="#current_address" aria-expanded="false" aria-controls="current_address" onclick="show_address(this)">
                                            <label for="customer">Current Address</label><br>
                        
                                            <input type="radio"  name="role" value="another_address" required=True data-toggle="collapse" data-target="#add_address" aria-expanded="false" aria-controls="add_address" onclick="show_address(this)">
                                            <label for="technician">Another Address</label><br>
                                        </div>
                                        
                                    </fieldset>
                                </div>  
                                </div>
                                
                                
                                
                            </form>  
                            <div class="form-row flex-main " id = "display_address" style="">
                                {%if AddressForm %}
                                {{AddressForm}}
                                {%endif%}
                            </div>
                            <div class="form-row" id="show-address-form">
                                
                            </div>
                            <button type="submit" class="btn btn-primary" form="newjob">Submit</button>         
                        {%endif%}
                   
                </div>

             
                <div id="display" class="">
                </div>
        </main>
    </div>
    </div>
</div>

<script type ="text/javascript" src="{% static 'google.js' %}"></script>
<script type ="text/javascript" src="{% static 'util.js' %}"></script>
<script type ="text/javascript" src="{% static 'function.js' %}"></script>
<script type ="text/javascript" src="{% static 'ad.js' %}"></script>
<script type ="text/javascript" src="{% static 'index.js' %}"></script>   

{%endblock%}

advertisement/templates/advertisement/appointment.html
{% extends "layout.html" %}

{% block title %}
    Posts
{% endblock %}
{% load static %}
{% block head %}
<script type ="text/javascript" src="{% static 'util.js' %}"></script>
<script type ="text/javascript" src="{% static 'function.js' %}"></script>




{%endblock%}
{% block body %}
    {%if appointment %}

    
    <div class="container">
        <div class="row">
            <main class="col-md-9  col-lg-10 px-md-4 ">
                
                <div class="container card pt-5 mt-5 rounded  job-communication-block " id="appointment-{{appointment.id}}">
                    {% if review%}
                    <a href="{% url 'advertisement:review' id=appointment.id %}" class="text-right">review</a>
                    {%endif%}
                    {%if send_review %}
                    <a class="text-right text-success">You have reviewed</a>
                    {%endif%}
                    <div id="headline" class="card-title p-0 m-0 ">
                        <!-- about job -->
                       <h1 id="title-job"> 
                           <a href="{% url 'advertisement:job_profile' type=appointment.Job.Job_type|title id=appointment.Job.id %}">{{appointment.Job.Job_type|title}}</a>
                       </h1>
                       <span>
                        
                            <i class="fa fa-map-marker" >  
                                {% if appointment.Job.Location %}
                                {{appointment.Job.Location.Line1}},
                                {%if appointment.Job.Location.Line2 %}
                                    {{appointment.Job.Location.Line2}},
                                {%endif%}
                                {{appointment.Job.Location.City}}, {{appointment.Job.Location.State}}, {{appointment.Job.Location.Country}}, {{appointment.Job.Location.Zipcode}}
                                {%endif%}
                            </i> 
                        </span>
                        <hr>
                        <div class="scheduled-job-technician">
                       
                            <h1 id="scheduled-technician">
                                {{"Technician:"|title}}
                                <span id="scheduled-technician">
                                   <p>
                                    <a href="{% url 'account:user_profile' username=appointment.Technician.username id=appointment.Technician.id|slugify %}">{{appointment.Technician.username|title}}</a>
                                   </p> 
                                </span>
                                
                            </h1>  
                       </div>
                       <div class="scheduled-job-customer">
                       
                        <h1 id="scheduled-customer">
                            {{"Customer:"|title}}
                            <span id="scheduled-customer">
                               <p>

                                   <a href="{% url 'account:user_profile' username=appointment.Jobresponse.Customer.username id=appointment.Jobresponse.Customer.id|slugify %}">{{appointment.Jobresponse.Customer.username|title}}</a>
                               </p> 
                            </span>
                            
                        </h1>  
                   </div>

                       <div class="scheduled-job-message">
                       
                        <h1 id="scheduled-job-message">
                            {{"Message:"|title}}
                            <span id="scheduled-job-message">
                               <p>
                                {{appointment.Jobresponse.Message}}
                               </p> 
                            </span>
                            
                        </h1>  
                   </div>
                       <div class="scheduled-job-time-date">
                    
                            <h1 id="scheduled-date-time">
                                {{"Scheduled date & time:"|title}}
                               <span id ="scheduled-date-time"> 
                                <p>{{appointment.Jobresponse.Date}} & Time: {{appointment.Jobresponse.Time}}</p>
                               </span>
                           </h1>
                       </div>
                       <div class="scheduled-job-budget">
                        <h1 id="scheduled-budget">
                            {{"Budget:"|title}}
                            <span id ="scheduled-budget">
                                <p >{{appointment.Jobresponse.Amount}} {{appointment.Jobresponse.Currency}}</p>
                            </span>
                            </h1> 
                        </div>     
                   </div>
                  

                </div>
               
            </main>
        </div>
    </div>
    {%endif%}
{%endblock%}